version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing Dependecies
      - npm install
  build:
    on-failure: ABORT
    commands:
      - echo Building Application
      - npm run build
  post_build:
    commands:
      - echo Build Completed. Copying files to S3
      - aws s3 cp dist s3://dnc-aula-frontend/ --recursive
artifacts:
  files:
    - "**/*"
  base-directory: dist
cache:
  paths:
    - "node_modules/**/*"
